//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudEDUServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LESSON
    {
        public LESSON()
        {
            this.DOCUMENTs = new HashSet<DOCUMENT>();
            this.NOTEs = new HashSet<NOTE>();
            this.ATTENDs = new HashSet<ATTEND>();
            this.RESOURCEs = new HashSet<RESOURCE>();
        }
    
        public int COURSE_ID { get; set; }
        public int ID { get; set; }
        public string CONTENT { get; set; }
        public string TITLE { get; set; }
        public int NUMBER { get; set; }
    
        public virtual COURSE COURSE { get; set; }
        public virtual ICollection<DOCUMENT> DOCUMENTs { get; set; }
        public virtual ICollection<NOTE> NOTEs { get; set; }
        public virtual ICollection<ATTEND> ATTENDs { get; set; }
        public virtual ICollection<RESOURCE> RESOURCEs { get; set; }
    }
}
