//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudEDUServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECOMMENDATION
    {
        public RECOMMENDATION()
        {
            this.COURSEs = new HashSet<COURSE>();
        }
    
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public string ICON_URL { get; set; }
    
        public virtual ICollection<COURSE> COURSEs { get; set; }
    }
}
